import sys
import os
import unittest
from unittest.mock import patch
import pandas as pd
import numpy as np

sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'src'))
from pd_model import apply_woe_transformation, compute_calibration_table

class TestPDModel(unittest.TestCase):
    def test_apply_woe_transformation_fallback(self):
        """Test the fallback path when bin edge extraction fails (e.g., KeyError)."""
        # Create a dummy dataframe with a continuous feature (nunique > 10)
        df = pd.DataFrame({
            "continuous_feat": range(20)
        })

        # Create woe_results where woe_table is missing the 'bin' column
        # This will trigger a KeyError in the try block
        woe_results = {
            "continuous_feat": {
                "woe_map": {"5": 0.5, "15": 1.5},
                "woe_table": pd.DataFrame({"not_bin": [1, 2]}) # Missing 'bin' column
            }
        }

        selected_features = ["continuous_feat"]

        # Apply transformation
        result = apply_woe_transformation(df, woe_results, selected_features)

        # It should fall back to string-based mapping
        # Value 5 string -> 0.5, Value 15 string -> 1.5, rest -> 0.0
        self.assertEqual(result.loc[5, "continuous_feat_woe"], 0.5)
        self.assertEqual(result.loc[15, "continuous_feat_woe"], 1.5)
        self.assertEqual(result.loc[0, "continuous_feat_woe"], 0.0)
        self.assertEqual(result.loc[19, "continuous_feat_woe"], 0.0)

    @patch("pandas.qcut")
    def test_compute_calibration_table_fallback(self, mock_qcut):
        """Test the fallback path when qcut fails with ValueError."""
        # Force pd.qcut to raise ValueError to simulate the error condition
        mock_qcut.side_effect = ValueError("Bin edges must be unique")

        y_true = np.array([0, 1, 0, 1, 0, 1])
        y_pred = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

        # This should use pd.cut instead of failing
        result = compute_calibration_table(y_true, y_pred, n_bins=2)

        # Assert qcut was called
        mock_qcut.assert_called_once()

        # Assert the result is a non-empty DataFrame generated by pd.cut
        self.assertIsInstance(result, pd.DataFrame)
        self.assertTrue(len(result) > 0)
        self.assertIn("avg_predicted_pd", result.columns)
        self.assertIn("actual_default_rate", result.columns)

        # For identical predictions, there should be 1 row with counts and 1 row with 0 counts
        # (or just 1 row overall depending on how pd.cut bins it and groupby drops observed=True)
        # We can just verify the overall prediction average
        valid_rows = result[result["count"] > 0]
        self.assertAlmostEqual(valid_rows["avg_predicted_pd"].iloc[0], 0.5)


if __name__ == "__main__":
    unittest.main()
